=== AntonBogdanov3000/EpamJavaTraining/WebApp/src/main/resources/medicins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        elementFormDefault="qualified"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/medicins"
        xmlns:tns="http://www.training.by/medicins">
    <element name="medicins">
        <complexType>
            <sequence>
                <element name="medicins" type="tns:Medicins"
                         minOccurs="1"
                         maxOccurs="16" />
            </sequence>
        </complexType>
    </element>
    <complexType name="Medicins">
        <sequence>
            <element name="name" type="string" />
            <element name="pharm" type="string" />
            <element name="group" type="tns:Group"/>
            <element name="analogs" type="string" />
            <element name="versions" type="tns:Version" />
            <element name="certificate" type="tns:Certificate" />
            <element name="package" type="tns:Package" />
            <element name="dosage" type="tns:Dosage" />
        </sequence>
        <attribute name="name" type="string" use="required" />
        </complexType>
    <simpleType name="Group" >
        <restriction base="string">
            <enumeration value="Antibiotic"/>
            <enumeration value="Analgesic" />
            <enumeration value="Antidepressant" />
            <enumeration value="Stimulant" />
            <enumeration value="Cardiovascular" />
            <enumeration value="Antiviral" />
        </restriction>
    </simpleType>
    <simpleType name="Version">
        <restriction base="string">
            <enumeration value="tablet" />
            <enumeration value="capsule" />
            <enumeration value="mixture" />
            <enumeration value="powder" />
        </restriction>
    </simpleType>
    <complexType name="Certificate">
        <sequence>
            <element name="number" type="long"/>
            <element name="date_of_issue" type="date" />
            <element name="expiry_date" type="date" />
            <element name="organization" type="string" />
        </sequence>
    </complexType>
    <complexType name="Package">
        <sequence>
            <element name="package_type">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="blister"/>
                        <enumeration value="tube"/>
                        <enumeration value="bottle"/>
                        <enumeration value="ampoule"/>
                        <enumeration value="syringe"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="count" type="int" />
            <element name="price" type="double" />
        </sequence>
    </complexType>
    <complexType name="Dosage">
        <sequence>
            <element name="dose" type="double" />
            <element name="use" type="string" />
        </sequence>
    </complexType>
</schema>

=== AntonBogdanov3000/EpamJavaTraining/WebApp/src/main/resources/medicins.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicins    xmlns="http://www.training.by/medicins"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://www.training.by/medicins medicins.xsd">

    <medicins name="Aspirine">
        <name>Aspirine</name>
        <pharm>Phizer</pharm>
        <group>Antibiotic</group>
        <analogs>Aspirine</analogs>
        <versions>tablet</versions>
        <certificate>
            <number>23</number>
            <date_of_issue>2010-05-20</date_of_issue>
            <expiry_date>2015-05-20</expiry_date>
            <organization>Belpharm</organization>
        </certificate>
        <package>
            <package_type>blister</package_type>
            <count>10</count>
            <price>15</price>
        </package>
        <dosage>
            <dose>5</dose>
            <use>2 times in a day</use>
        </dosage>
    </medicins>
    <medicins name="Coldrex">
        <name>Coldrex</name>
        <pharm>SmithKline</pharm>
        <group>Analgesic</group>
        <analogs>Theraflu</analogs>
        <versions>powder</versions>
        <certificate>
            <number>34</number>
            <date_of_issue>2006-06-09</date_of_issue>
            <expiry_date>2016-06-09</expiry_date>
            <organization>Belpharm</organization>
        </certificate>
        <package>
            <package_type>syringe</package_type>
            <count>12</count>
            <price>8</price>
        </package>
        <dosage>
            <dose>10</dose>
            <use>if body temperature is high</use>
        </dosage>
    </medicins>
    <medicins name="Theraflu">
        <name>Theraflu</name>
        <pharm>GSK US</pharm>
        <group>Analgesic</group>
        <analogs>Coldrex</analogs>
        <versions>powder</versions>
        <certificate>
            <number>127</number>
            <date_of_issue>2013-07-04</date_of_issue>
            <expiry_date>2013-07-04</expiry_date>
            <organization>Belpharm</organization>
        </certificate>
        <package>
            <package_type>syringe</package_type>
            <count>10</count>
            <price>12</price>
        </package>
        <dosage>
            <dose>10</dose>
            <use>if body temperature is high</use>
        </dosage>
    </medicins>
    <medicins name="Mig">
        <name>Mig</name>
        <pharm>Berlin-Chemie</pharm>
        <group>Antiviral</group>
        <analogs>Citramon</analogs>
        <versions>tablet</versions>
        <certificate>
            <number>47</number>
            <date_of_issue>2020-03-12</date_of_issue>
            <expiry_date>2025-03-11</expiry_date>
            <organization>Belpharm</organization>
        </certificate>
        <package>
            <package_type>blister</package_type>
            <count>10</count>
            <price>7</price>
        </package>
        <dosage>
            <dose>5</dose>
            <use>one time in a day</use>
        </dosage>
    </medicins>
    </medicins>
